server:
  port: 8086
spring:
  application:
    name: invoice-service
  datasource:
    url: jdbc:postgresql://localhost:5432/taxlot_invoice
    username: postgres
    password: password
  flyway:
    enabled: true
    baseline-on-migrate: true
  rabbitmq:
    host: localhost
    port: 5672
  jackson:
    property-naming-strategy: SNAKE_CASE
    serialization:
      write-dates-as-timestamps: false
