server:
  port: 8087

spring:
  application:
    name: payment-service
  datasource:
    url: jdbc:postgresql://localhost:5432/taxlot_payment
    username: postgres
    password: password
  flyway:
    enabled: true
    baseline-on-migrate: true
  rabbitmq:
    host: localhost
    port: 5672
  jackson:
    serialization:
      write-dates-as-timestamps: false

taxlot:
  events:
    exchange: taxlot.events
