CREATE TABLE permissions (
    id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name        VARCHAR(100) NOT NULL UNIQUE,
    description VARCHAR(255)
);

CREATE TABLE role_permissions (
    role_name       member_role NOT NULL,
    permission_name VARCHAR(100) NOT NULL REFERENCES permissions(name),
    PRIMARY KEY (role_name, permission_name)
);

INSERT INTO permissions(name, description) VALUES
    ('organization.read',   'View organization details'),
    ('organization.update', 'Update organization settings'),
    ('member.read',         'View members'),
    ('member.invite',       'Invite new members'),
    ('member.remove',       'Remove members'),
    ('customer.read',       'View customers'),
    ('customer.create',     'Create customers'),
    ('customer.update',     'Update customers'),
    ('customer.delete',     'Delete customers'),
    ('invoice.read',        'View invoices'),
    ('invoice.create',      'Create invoices'),
    ('invoice.issue',       'Issue invoices'),
    ('invoice.cancel',      'Cancel invoices'),
    ('expense.read',        'View expenses'),
    ('expense.create',      'Create expenses'),
    ('expense.approve',     'Approve expenses'),
    ('payment.read',        'View payments'),
    ('payment.create',      'Record payments'),
    ('accounting.read',     'View accounting data'),
    ('accounting.post',     'Post journal entries'),
    ('report.read',         'View reports'),
    ('tax.read',            'View tax information'),
    ('tax.manage',          'Manage tax configuration');

INSERT INTO role_permissions(role_name, permission_name) VALUES
    ('OWNER', 'organization.read'), ('OWNER', 'organization.update'),
    ('OWNER', 'member.read'), ('OWNER', 'member.invite'), ('OWNER', 'member.remove'),
    ('OWNER', 'customer.read'), ('OWNER', 'customer.create'), ('OWNER', 'customer.update'), ('OWNER', 'customer.delete'),
    ('OWNER', 'invoice.read'), ('OWNER', 'invoice.create'), ('OWNER', 'invoice.issue'), ('OWNER', 'invoice.cancel'),
    ('OWNER', 'expense.read'), ('OWNER', 'expense.create'), ('OWNER', 'expense.approve'),
    ('OWNER', 'payment.read'), ('OWNER', 'payment.create'),
    ('OWNER', 'accounting.read'), ('OWNER', 'accounting.post'),
    ('OWNER', 'report.read'), ('OWNER', 'tax.read'), ('OWNER', 'tax.manage'),
    ('ADMIN', 'organization.read'), ('ADMIN', 'organization.update'),
    ('ADMIN', 'member.read'), ('ADMIN', 'member.invite'), ('ADMIN', 'member.remove'),
    ('ADMIN', 'customer.read'), ('ADMIN', 'customer.create'), ('ADMIN', 'customer.update'), ('ADMIN', 'customer.delete'),
    ('ADMIN', 'invoice.read'), ('ADMIN', 'invoice.create'), ('ADMIN', 'invoice.issue'), ('ADMIN', 'invoice.cancel'),
    ('ADMIN', 'expense.read'), ('ADMIN', 'expense.create'), ('ADMIN', 'expense.approve'),
    ('ADMIN', 'payment.read'), ('ADMIN', 'payment.create'),
    ('ADMIN', 'accounting.read'), ('ADMIN', 'accounting.post'),
    ('ADMIN', 'report.read'), ('ADMIN', 'tax.read'), ('ADMIN', 'tax.manage'),
    ('ACCOUNTANT', 'organization.read'),
    ('ACCOUNTANT', 'customer.read'), ('ACCOUNTANT', 'customer.create'), ('ACCOUNTANT', 'customer.update'),
    ('ACCOUNTANT', 'invoice.read'), ('ACCOUNTANT', 'invoice.create'), ('ACCOUNTANT', 'invoice.issue'), ('ACCOUNTANT', 'invoice.cancel'),
    ('ACCOUNTANT', 'expense.read'), ('ACCOUNTANT', 'expense.approve'),
    ('ACCOUNTANT', 'payment.read'), ('ACCOUNTANT', 'payment.create'),
    ('ACCOUNTANT', 'accounting.read'), ('ACCOUNTANT', 'accounting.post'),
    ('ACCOUNTANT', 'report.read'), ('ACCOUNTANT', 'tax.read'), ('ACCOUNTANT', 'tax.manage'),
    ('STAFF', 'organization.read'),
    ('STAFF', 'customer.read'), ('STAFF', 'customer.create'), ('STAFF', 'customer.update'),
    ('STAFF', 'invoice.read'), ('STAFF', 'invoice.create'),
    ('STAFF', 'expense.read'), ('STAFF', 'expense.create'),
    ('STAFF', 'payment.read'),
    ('AUDITOR', 'organization.read'),
    ('AUDITOR', 'customer.read'),
    ('AUDITOR', 'invoice.read'),
    ('AUDITOR', 'expense.read'),
    ('AUDITOR', 'payment.read'),
    ('AUDITOR', 'accounting.read'),
    ('AUDITOR', 'report.read'),
    ('AUDITOR', 'tax.read');
